### ISSUE TITLE
Error loading platform - UNIT_UV_INDEX

### ISSUE THREAD

**Issue by xstrex** [shbatm/hacs-isy994#53]
HA Version: 0.109.0
Platform Version: 1.3.6

Logs: (related to isy994, the first entry is to be expected)

```
2020-04-29 12:07:03 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for isy994 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-04-29 12:07:10 ERROR (MainThread) [homeassistant.setup] Setup failed for isy994: Unable to import component: cannot import name 'UNIT_UV_INDEX' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
2020-04-29 12:08:04 WARNING (MainThread) [homeassistant.helpers.translation] isy994: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-04-29 12:09:33 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 125, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 88, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_remove
    unload_success = await self.async_unload(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 704, in async_unload
    return await entry.async_unload(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 272, in async_unload
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 270, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/isy994/__init__.py", line 50, in <module>
    from .const import (
  File "/config/custom_components/isy994/const.py", line 21, in <module>
    from homeassistant.const import (
ImportError: cannot import name 'UNIT_UV_INDEX' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

**Comment by bkvargyas** [comment]
I just upgraded as well, and ran into the same error.

**Comment by xstrex** [comment]
Identical issue, see https://github.com/shbatm/hacs-isy994/issues/52

**Comment by shbatm** [comment]
Pushed [1.3.7](https://github.com/shbatm/hacs-isy994/releases/tag/v1.3.7) which should fix this. It's still marked as a Beta release for the moment (so make sure to enable "Show Betas" in HACS). As soon as I get a chance to fully test I'll mark it as a full release.

**Comment by pashdown** [comment]
Version 1.3.7 with Home Assistant 0.109.4.  Still have this problem.

**Comment by shbatm** [comment]
Please double check that HACS actually completed the update to 1.3.7: the change was definitely in there:
https://github.com/shbatm/hacs-isy994/blob/9f0d0bfefdf67835c96cbec4f9a13157c7d78a77/custom_components/isy994/const.py#L61

Sometimes HACS doesn't get the update right.
